I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 30, in script call
    call s1
  File "game/s1.rpy", line 75, in script
    Z "*scoffs* HA!\nImpudent Mortal"
Exception: Sayer 'Z' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 30, in script call
    call s1
  File "game/s1.rpy", line 75, in script
    Z "*scoffs* HA!\nImpudent Mortal"
  File "renpy/ast.py", line 680, in execute
    who = eval_who(self.who, self.who_fast)
  File "renpy/ast.py", line 574, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'Z' is not defined.

Windows-10-10.0.19041
Ren'Py 7.4.4.1439
ICS166 Project 1.0
Sat May 29 14:59:37 2021
